version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blankfactor
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bfuser
      MYSQL_PASSWORD: bfpassword
    volumes:
      - ./dump:/docker-entrypoint-initdb.d